(defun delete-pic() (interactive)
  (let (filepath)
  (when (org-in-regexp org-bracket-link-regexp 1)
    (progn
      (setq filepath (org-link-unescape (org-match-string-no-properties 1)))
      (delete-region (match-beginning 0) (match-end 0))
      (setq filepath (replace-regexp-in-string "file:" "" filepath))
      (message (concat filepath " wird gelöscht"))
      (delete-file filepath)
      ))))
(provide 'delete-pic)
