(setq-default filesets-be-docile-flag 'nil)

(setq filesets-submenus '("org" ("0 org" ["Files: org" (filesets-open (quote :files) (quote "org"))] "---" ["0 elementare_stochastik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/elementare_stochastik.org") (quote "org"))] ["1 emacs_config.org" (filesets-file-open nil (quote "/home/florian/.emacs.d/emacs_config.org") (quote "org"))] ["2 logik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/logik.org") (quote "org"))] ["3 organisation.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/organisation.org") (quote "org"))] ["4 refile.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/refile.org") (quote "org"))] ["5 theoretische_informatik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/theoretische_informatik.org") (quote "org"))] ["6 todo.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/todo.org") (quote "org"))] ["7 webdesign.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/webdesign.org") (quote "org"))] "---" ["Close all files" (filesets-close (quote :files) (quote "org"))] ["Run Command" (filesets-run-cmd nil (quote "org") (quote :files))] ["Add current buffer" (filesets-add-buffer (quote "org") (current-buffer))] ["Remove current buffer" (filesets-remove-buffer (quote "org") (current-buffer))] ["Rebuild this submenu" (filesets-rebuild-this-submenu (quote "org"))])))

(setq filesets-menu-cache '(("0 org" ["Files: org" (filesets-open (quote :files) (quote "org"))] "---" ["0 elementare_stochastik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/elementare_stochastik.org") (quote "org"))] ["1 emacs_config.org" (filesets-file-open nil (quote "/home/florian/.emacs.d/emacs_config.org") (quote "org"))] ["2 logik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/logik.org") (quote "org"))] ["3 organisation.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/organisation.org") (quote "org"))] ["4 refile.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/refile.org") (quote "org"))] ["5 theoretische_informatik.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/theoretische_informatik.org") (quote "org"))] ["6 todo.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/todo.org") (quote "org"))] ["7 webdesign.org" (filesets-file-open nil (quote "/home/florian/Zettelkasten/webdesign.org") (quote "org"))] "---" ["Close all files" (filesets-close (quote :files) (quote "org"))] ["Run Command" (filesets-run-cmd nil (quote "org") (quote :files))] ["Add current buffer" (filesets-add-buffer (quote "org") (current-buffer))] ["Remove current buffer" (filesets-remove-buffer (quote "org") (current-buffer))] ["Rebuild this submenu" (filesets-rebuild-this-submenu (quote "org"))])))

(setq filesets-ingroup-cache 'nil)

(setq filesets-cache-version "1.8.4")

